print(type('Meu nome é Juliano!'))
print(type('Python'))
print(type('500'))
print(5 + int('5'))
print(str(2))
print('50' + '10')
print('olá ' + 'juliano')
print('Python' * 3)
print(len('juliano'))
help(print)
help(str)
